version: '3.7'
services:
  app:
    build: .
    environment:
      - SESSION_SECRET=sdfasdfsfd
      - DB_USERNAME=profesio
      - DB_PASSWORD=profesio
      - DB_DATABASE=profesio
      - DB_HOST=db
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=profesio
      - POSTGRES_USER=profesio
      - POSTGRES_DB=profesio