version: '3.7'
services:
  app:
    build: .
    command: sh -c "yarn db:runmigrations && yarn start" 
    environment:
      - SESSION_SECRET=sdfasdfsfd
      - DB_USERNAME=profesio
      - DB_PASSWORD=profesio
      - DB_DATABASE=profesio
      - DB_HOST=postgres
    depends_on:
      - postgres
    ports:
      - 3000:3000

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=profesio
      - POSTGRES_USER=profesio
      - POSTGRES_DB=profesio